@startuml test

class Test {
    - int myvar
    - String myvar2
    - String pleasePleaseFinallyWorkNow
    - boolean thisShouldWorkNow
    - boolean areWeDoneYet
    {static} + main(String[] args)
}

@enduml
