name: Google Style Guide Verification

on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: checkstyle
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-review'
        checkstyle_config: 'google_checks.xml'
        fail_on_error: true
        tool_name: 'checkstyles'
