name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(find | grep ${{ env.UML_FILES }} | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng ${{ steps.getfile.outputs.files }}
      - name: Stage Local Changes to Commit
        run: git status; git add *; git status
      - name: Commit PlantUML Diagrams
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate SVG and PNG images for PlantUML diagrams\n\nrequest-checks: true"
      - name: Restart Google Style Guide Verification
        run: curl -X POST https://api.github.com/repos/andrewdimmer/csi-3370-software-project-config-test/check-runs?name=checkstyle&head_sha=6fc540b1704562def3b070404ba5ef2094feb618
        #uses: benc-uk/workflow-dispatch@v1
        #with:
          #workflow: Google Style Guide Verification
          #token: ${{ secrets.PERSONAL_TOKEN }}
