name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(find | grep ${{ env.UML_FILES }} | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng ${{ steps.getfile.outputs.files }}
      - name: Stage Local Changes to Commit
        run: git status; git add *; git status
      - name: Commit PlantUML Diagrams
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate SVG and PNG Images for PlantUML Diagrams
  post-plantuml-checkstyle:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Pull Changes and Save the Newest Commit's Hash
        run:
          curl https://api.github.com/repos/andrewdimmer/csi-3370-software-project-config-test/commits/$(git rev-parse HEAD)/check-runs | python3 .github/github_action_workflow_to_job_id.py "post-plantuml-checkstyle" > jobrunid.txt;
          echo Job Run Id $(cat jobrunid.txt);
          echo JOB_RUN_ID=$(cat jobrunid.txt) >> $GITHUB_ENV;
          echo Branch ${{github.event.pull_request.head.ref}};
          git fetch ${{github.event.pull_request.head.ref}};
          echo New SHA $(git rev-parse HEAD);
          echo NEW_SHA=$(git rev-parse HEAD) >> $GITHUB_ENV;
      - name: Restart Google Style Guide Verification
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'google_checks.xml'
          fail_on_error: true
          tool_name: 'checkstyle'
      - name: Report Checkstyles Success to Pull Request
        if: ${{ success() }}
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: checkstyle
          state: 'success'
          sha: ${{env.NEW_SHA}}
          target_url: https://github.com/andrewdimmer/csi-3370-software-project-config-test/runs/${{env.JOB_RUN_ID}}
      - name: Report Checkstyles Failure to Pull Request
        if: ${{ failure() }}
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: checkstyle
          state: 'failure'
          sha: ${{env.NEW_SHA}}
          target_url: https://github.com/andrewdimmer/csi-3370-software-project-config-test/runs/${{env.JOB_RUN_ID}}
